Criaturas= [
    # Columna Izquierda
    {"name": "Ceto", "killer": "-", "description": "Criatura marina primordial.", "captured": None},
    {"name": "Tifón", "killer": "Zeus", "description": "Monstruo gigante y temible de la mitología.", "captured": None},
    {"name": "Equidna", "killer": "Argos Panoptes", "description": "Madre de numerosos monstruos.", "captured": None},
    {"name": "Dino", "killer": "-", "description": "Una de las Grayas.", "captured": None},
    {"name": "Pefredo", "killer": "-", "description": "Una de las Grayas.", "captured": None},
    {"name": "Enio", "killer": "-", "description": "Una de las Grayas.", "captured": None},
    {"name": "Escila", "killer": "-", "description": "Monstruo marino con forma de terrorífica criatura.", "captured": None},
    {"name": "Caribdis", "killer": "-", "description": "Monstruo marino que tragaba grandes cantidades de agua.", "captured": None},
    {"name": "Euríale", "killer": "-", "description": "Una de las Gorgonas, hermana de Medusa.", "captured": None},
    {"name": "Esteno", "killer": "-", "description": "Una de las Gorgonas.", "captured": None},
    {"name": "Medusa", "killer": "Perseo", "description": "Gorgona cuya mirada convertía en piedra.", "captured": None},
    {"name": "Ladón", "killer": "Heracles", "description": "Dragón de cien cabezas que custodiaba el jardín de las Hespérides.", "captured": None},
    {"name": "Águila del Cáucaso", "killer": "-", "description": "Águila que tormentaba a Prometeo.", "captured": None},
    {"name": "Quimera", "killer": "Belerofonte", "description": "Monstruo híbrido que echaba fuego por la boca.", "captured": None},
    {"name": "Hidra de Lerna", "killer": "Heracles", "description": "Monstruo acuario de múltiples cabezas.", "captured": None},
    {"name": "León de Nemea", "killer": "Heracles", "description": "Bestia con piel impenetrable.", "captured": None},
    {"name": "Esfinge", "killer": "Edipo", "description": "Criatura con rostro de mujer y cuerpo de león que proponía acertijos.", "captured": None},
    {"name": "Dragón de la Cólquida", "killer": "-", "description": "Dragón que custodiaba el Vellocino de Oro.", "captured": None},
    {"name": "Cerbero", "killer": "-", "description": "Perro de Hades de tres cabezas.", "captured": None},
    
    # Columna Derecha
    {"name": "Cerda de Cromión", "killer": "Teseo", "description": "Feroz jabalí/cerda hembra asolaba Cromión.", "captured": None},
    {"name": "Ortro", "killer": "Heracles", "description": "Perro bicéfalo hermano de Cerbero.", "captured": None},
    {"name": "Toro de Creta", "killer": "Teseo", "description": "Toro salvaje enviado por Poseidón.", "captured": None},
    {"name": "Jabalí de Calidón", "killer": "Atalanta", "description": "Monstruosa bestia enviada por Artemisa.", "captured": None},
    {"name": "Carcinos", "killer": "-", "description": "Cangrejo gigante que ayudó a la Hidra.", "captured": None},
    {"name": "Gerión", "killer": "Heracles", "description": "Gigante de tres cuerpos.", "captured": None},
    {"name": "Cloto", "killer": "-", "description": "Una de las Moiras.", "captured": None},
    {"name": "Láquesis", "killer": "-", "description": "Una de las Moiras.", "captured": None},
    {"name": "Átropos", "killer": "-", "description": "Una de las Moiras.", "captured": None},
    {"name": "Minotauro de Creta", "killer": "Teseo", "description": "Criatura con cabeza de toro y cuerpo de hombre.", "captured": None},
    {"name": "Harpías", "killer": "-", "description": "Criaturas con cuerpo de ave y rostro de mujer.", "captured": None},
    {"name": "Argos Panoptes", "killer": "Hermes", "description": "Gigante de cien ojos.", "captured": None},
    {"name": "Aves del Estínfalo", "killer": "-", "description": "Aves con plumas de bronce.", "captured": None},
    {"name": "Talos", "killer": "Medea", "description": "Gigante autómata de bronce que protegía Creta.", "captured": None},
    {"name": "Sirenas", "killer": "-", "description": "Criaturas que atraían a los marineros con sus cantos.", "captured": None},
    {"name": "Pitón", "killer": "Apolo", "description": "Gran serpiente de Delfos.", "captured": None},
    {"name": "Cierva de Cerinea", "killer": "-", "description": "Cierva con cornamenta de oro consagrada a Artemisa.", "captured": None},
    {"name": "Basilisco", "killer": "-", "description": "Rey de las serpientes capaz de matar con la mirada.", "captured": None},
    {"name": "Jabalí de Erimanto", "killer": "-", "description": "Enorme jabalí que habitaba en el monte Erimanto.", "captured": None}
]