Criaturas= [
    # Columna Izquierda
    {"name": "Ceto", "killer": "-", "description": "", "captured": None},
    {"name": "Tifón", "killer": "Zeus", "description": "", "captured": None},
    {"name": "Equidna", "killer": "Argos Panoptes", "description":"", "captured": None},
    {"name": "Dino", "killer": "-", "description": "", "captured": None},
    {"name": "Pefredo", "killer": "-", "description": "", "captured": None},
    {"name": "Enio", "killer": "-", "description": "", "captured": None},
    {"name": "Escila", "killer": "-", "description": "", "captured": None},
    {"name": "Caribdis", "killer": "-", "description": "", "captured": None},
    {"name": "Euríale", "killer": "-", "description": "", "captured": None},
    {"name": "Esteno", "killer": "-", "description": "", "captured": None},
    {"name": "Medusa", "killer": "Perseo", "description": "", "captured": None},
    {"name": "Ladón", "killer": "Heracles", "description": "", "captured": None},
    {"name": "Águila del Cáucaso", "killer": "-", "description": "", "captured": None},
    {"name": "Quimera", "killer": "Belerofonte", "description": "", "captured": None},
    {"name": "Hidra de Lerna", "killer": "Heracles", "description": "", "captured": None},
    {"name": "León de Nemea", "killer": "Heracles", "description": "", "captured": None},
    {"name": "Esfinge", "killer": "Edipo", "description": "", "captured": None},
    {"name": "Dragón de la Cólquida", "killer": "-", "description": "", "captured": None},
    {"name": "Cerbero", "killer": "-", "description": "", "captured": None},
    
    # Columna Derecha
    {"name": "Cerda de Cromión", "killer": "Teseo", "description": "", "captured": None},
    {"name": "Ortro", "killer": "Heracles", "description": "", "captured": None},
    {"name": "Toro de Creta", "killer": "Teseo", "description": "", "captured": None},
    {"name": "Jabalí de Calidón", "killer": "Atalanta", "description": "", "captured": None},
    {"name": "Carcinos", "killer": "-", "description": "", "captured": None},
    {"name": "Gerión", "killer": "Heracles", "description": "", "captured": None},
    {"name": "Cloto", "killer": "-", "description": "", "captured": None},
    {"name": "Láquesis", "killer": "-", "description": "", "captured": None},
    {"name": "Átropos", "killer": "-", "description": "", "captured": None},
    {"name": "Minotauro de Creta", "killer": "Teseo", "description": "", "captured": None},
    {"name": "Harpías", "killer": "-", "description": "", "captured": None},
    {"name": "Argos Panoptes", "killer": "Hermes", "description": "", "captured": None},
    {"name": "Aves del Estínfalo", "killer": "-", "description": "", "captured": None},
    {"name": "Talos", "killer": "Medea", "description": "", "captured": None},
    {"name": "Sirenas", "killer": "-", "description": "", "captured": None},
    {"name": "Pitón", "killer": "Apolo", "description": "", "captured": None},
    {"name": "Cierva de Cerinea", "killer": "-", "description": "", "captured": None},
    {"name": "Basilisco", "killer": "-", "description": "", "captured": None},
    {"name": "Jabalí de Erimanto", "killer": "-", "description": "", "captured": None}
]